import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Sidebar items generated by docusaurus-plugin-openapi-docs from docs/openapi.yaml
// Regenerate via: npm run docusaurus gen-api-docs all
const apiSidebar = require('./docs/api/sidebar.ts');

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'getting-started',
    'authentication',
    'development',
    'troubleshooting',
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        slug: '/api',
      },
      items: apiSidebar,
    },
  ],
};

export default sidebars;
